<a href="https://colab.research.google.com/github/CindyYWangH/pb_Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python for Data Analysis

The possibilities of Python are very many. You can code web applications, small programs or software, etc. But if you want to focus on Data Science, you will need to know some more **tools**. These tools come with **libraries**. In this section, we will introduce two essential libraries: **Numpy and Pandas**. Clearly, no one claims doing **DS** without knowing them. Their purposes are similar, but they are very complementary and they work together. Their main goal is to provide data structures that will help you do more complex analysis or statistical processing.

**NumPy is the library for Numerical Python.** It is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc. It is also useful in linear algebra, random number capability, etc.


**NumPy Array**: NumPy array is a powerful n-dimensional array object which is in the form of rows and columns. We can initialise numpy arrays from nested python lists and access it elements.

## Numpy Array vs Python Lists 

We use Python NumPy array instead of a list because of the below reasons:
* Less Memory : The very first reason to choose Python NumPy array is that it occupies less memory as compared to list. 
* Then, it is pretty fast in terms of execution.

In [ ]:
import numpy as np

## Introduction to Numpy Arrays

In [ ]:
arr = np.array([1, 2, 3])
type(arr)


TypeError: ignored

In [ ]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(24,)

In [ ]:
k = a.reshape(2, 12)
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
k.ndim

2

### Exercise
1. Create an array with values between 10 and 30, increments by 2
2. Transform it to a 2 dimensional array

In [ ]:
arr = np.arange(10, 30, 2)
arr2 = arr.reshape(2,5)
arr2.ndim

2

In [ ]:
b = np.arange(36)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
c = b.reshape((3, 3, 4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(3, 3, 4)

In [ ]:
c.size

36

In [ ]:
c.dtype

dtype('int64')

In [ ]:
group = np.array([[29, 10, 40], [45, 9, 30], [34, 5, 35], [38, 4, 35]])
group

array([[29, 10, 40],
       [45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [ ]:
group.shape

(4, 3)

In [ ]:
group[-3]

array([45,  9, 30])

In [ ]:
#Print out the element 30
group[1][-1]


30

In [ ]:
group[0]

array([29, 10, 40])

In [ ]:
persons_data = [[29, 10, 40],
               [45, 9, 30],
               [34, 5, 35],
               [38, 4, 35]]
persons_data

[[29, 10, 40], [45, 9, 30], [34, 5, 35], [38, 4, 35]]

In [ ]:
persons_data[2]

[34, 5, 35]

In [ ]:
persons_data.shape

AttributeError: ignored

In [ ]:
numpy_group = np.array(persons_data)
numpy_group

array([[29, 10, 40],
       [45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [ ]:
numpy_group.shape

(4, 3)

In [ ]:
numpy_group[:,0]

array([29, 45, 34, 38])

In [ ]:
numpy_group[0,:]

array([29, 10, 40])

In [ ]:
#Last element in the lists (boxes)
numpy_group[:, -1]

array([40, 30, 35, 35])

In [ ]:
import numpy as np
a = np.array([[1,2], [3,4]])
print (a)
a.shape


[[1 2]
 [3 4]]


(2, 2)

In [ ]:
b = np.array([[5,6], [7,8]])
print (b)
b.shape

[[5 6]
 [7 8]]


(2, 2)

In [ ]:
c = np.append(a,b, axis =0)
print (c)
c.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)

In [ ]:
d = np.append (a,b, axis= 1)
print (d)
print (d.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [ ]:
numpy_group.mean()

26.166666666666668

In [ ]:
numpy_group.mean(axis=0)

array([36.5,  7. , 35. ])

In [ ]:
numpy_group.mean(axis = 1)

array([26.33333333, 28.        , 24.66666667, 25.66666667])

In [ ]:
np.array([3, 5, 7, 1, 9, 2.56])

array([3.  , 5.  , 7.  , 1.  , 9.  , 2.56])

#### Special Types of Arrays 

In [ ]:
import numpy as np

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(6).reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(18)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [ ]:
np.ones(18).reshape(3,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full((2, 3), 24)

array([[24, 24, 24],
       [24, 24, 24]])

In [ ]:
np.random.random((3, 6))

array([[0.75402568, 0.04350671, 0.03666515, 0.62197035, 0.42247664,
        0.86984268],
       [0.21826307, 0.0145039 , 0.20542815, 0.28255793, 0.84100282,
        0.87092274],
       [0.74866064, 0.42136789, 0.06292128, 0.93557556, 0.93344738,
        0.80732178]])

#### The Arange Method

In [ ]:
np.arange(0,20,5) #with the starting, stopping, and stepping arguments

array([ 0,  5, 10, 15])

#### Retrieving Data from an Array 

In [ ]:
numpy_group

array([[29, 10, 40],
       [45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [ ]:
numpy_group.ndim

2

In [ ]:
numpy_group[0]

array([29, 10, 40])

In [ ]:
numpy_group[-1]

array([38,  4, 35])

In [ ]:
numpy_group[0,2]

40

In [ ]:
numpy_group[0,2] = 1500

In [ ]:
numpy_group

array([[  29,   10, 1500],
       [  45,    9,   30],
       [  34,    5,   35],
       [  38,    4,   35]])

In [ ]:
numpy_group[0] = [30, 11, 100]
numpy_group

array([[ 30,  11, 100],
       [ 45,   9,  30],
       [ 34,   5,  35],
       [ 38,   4,  35]])

In [ ]:
numpy_group[:2]

array([[  30,   11, 1400],
       [  45,    9,   30]])

In [ ]:
numpy_group[2:]

array([[34,  5, 35],
       [38,  4, 35]])

In [ ]:
numpy_group[:]

array([[  30,   11, 1400],
       [  45,    9,   30],
       [  34,    5,   35],
       [  38,    4,   35]])

In [ ]:
numpy_group[-3:]

array([[45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [ ]:
numpy_group[0:4:2] #starting, stopping, and stepping args for rows

array([[  29,   10, 1500],
       [  34,    5,   35]])

In [ ]:
numpy_group[::-1]

array([[  38,    4,   35],
       [  34,    5,   35],
       [  45,    9,   30],
       [  30,   11, 1400]])

In [ ]:
numpy_group[0:3,1:3]

array([[  11, 1400],
       [   9,   30],
       [   5,   35]])

In [ ]:
numpy_group[:,2]

array([1400,   30,   35,   35])

In [ ]:
numpy_group

array([[  30,   11, 1400],
       [  45,    9,   30],
       [  34,    5,   35],
       [  38,    4,   35]])

In [ ]:
numpy_group[0:3:2, ::-122]

array([[1400],
       [  35]])

## Manipulating Numpy Arrays with Operators and Aggregate Functions 

### Basic Operators

In [ ]:
numpy_group

array([[ 30,  11, 100],
       [ 45,   9,  30],
       [ 34,   5,  35],
       [ 38,   4,  35]])

In [ ]:
numpy_group + 1

array([[ 31,  12, 101],
       [ 46,  10,  31],
       [ 35,   6,  36],
       [ 39,   5,  36]])

In [ ]:
numpy_group / 10

array([[ 3. ,  1.1, 10. ],
       [ 4.5,  0.9,  3. ],
       [ 3.4,  0.5,  3.5],
       [ 3.8,  0.4,  3.5]])

In [ ]:
numpy_group // 10

array([[ 3,  1, 10],
       [ 4,  0,  3],
       [ 3,  0,  3],
       [ 3,  0,  3]])

In [ ]:
numpy_group * 2

array([[ 60,  22, 200],
       [ 90,  18,  60],
       [ 68,  10,  70],
       [ 76,   8,  70]])

In [ ]:
#Adding two arrays of the same shape
print (numpy_group + numpy_group)

[[ 60  22 200]
 [ 90  18  60]
 [ 68  10  70]
 [ 76   8  70]]


In [ ]:
numpy_group - numpy_group

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Comparison Operators

In [ ]:
numpy_group

array([[29, 10, 40],
       [45,  9, 30],
       [34,  5, 35],
       [38,  4, 35]])

In [ ]:
numpy_group > 30

array([[False, False,  True],
       [ True, False, False],
       [ True, False,  True],
       [ True, False,  True]])

In [ ]:
numpy_group < 50

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
numpy_group >=11

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [ ]:
numpy_group <= 35

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [ ]:
numpy_group == 38

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

### Logical Operators

In [ ]:
(numpy_group > 30)

array([[False, False,  True],
       [ True, False, False],
       [ True, False,  True],
       [ True, False,  True]])

In [ ]:
(numpy_group <= 35)

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [ ]:
#The 'and' operator
(numpy_group > 30) & (numpy_group <= 35)

array([[False, False, False],
       [False, False, False],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
#The 'or' operator
(numpy_group <= 30) | (numpy_group > 35)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [ ]:
(numpy_group <= 30) | (numpy_group > 35)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

In [ ]:
#The 'negation' operator
#The tilda sign is used to represent the not operator
~((numpy_group <= 30) | (numpy_group > 35))

array([[False, False, False],
       [False, False, False],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
numpy_group

## Adding and Removing Elements from NumPy Arrays

* Append horizontally and vertically,
* Vertical stacking,
* Insert, and
* Delete

#### Append

In [ ]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b = np.append(a, [5,6,7,8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [ ]:
b.shape

(28,)

In [ ]:
b.reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [ ]:
c = np.arange(24).reshape(2,3,4)*10+3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
esther = np.arange(6).reshape(2,3)
esther

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
mike = np.arange(6, 18).reshape(4,3)
mike

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.append(esther, mike, axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
# Joining along the row (axis = 0)

np.append(a, c, axis = 0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
a.shape

(2, 3, 4)

In [ ]:
c.shape

(2, 3, 4)

In [ ]:
np.append(a, c, axis = 0).shape

(4, 3, 4)

In [ ]:
# Joining along the column (axis = 1)

np.append(a, c, axis = 1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
np.append(a, c, axis = 1).shape

(2, 6, 4)

In [ ]:
np.append(a, c, axis = 2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [ ]:
np.append(a,c, axis = 2).shape

(2, 3, 8)

#### Hstack

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
my_num = np.hstack((a,c))
my_num

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
my_num

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
my_num[0,0,2] = 999
my_num

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
mike

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
mike_insert = np.insert(mike, 1, 44, axis = 1)
mike_insert

array([[ 6, 44,  7,  8],
       [ 9, 44, 10, 11],
       [12, 44, 13, 14],
       [15, 44, 16, 17]])

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis = 0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis = 1)
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [ ]:
after_insert_array = np.insert(c, 1, 444, axis = 2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [ ]:
c.shape

(2, 3, 4)

In [ ]:
d = np.empty(c.shape)
d

array([[[1.32040844e-311, 7.31217156e-322, 0.00000000e+000,
         0.00000000e+000],
        [1.33511018e-306, 1.15998412e-028, 2.44171989e+232,
         8.00801729e+159],
        [8.16124052e-153, 6.03108138e-154, 6.01391519e-154,
         1.17633628e-095]],

       [[8.18920594e+140, 6.01347002e-154, 4.57669518e-072,
         1.03080550e+136],
        [6.01347002e-154, 1.03895280e-095, 5.79961843e+294,
         1.43267083e+161],
        [4.56317366e-144, 4.82412328e+228, 1.04718130e-142,
         1.11260652e-306]]])

In [ ]:
np.copyto(d,c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [ ]:
print(d)
print(c)

[[[  3.  13.  23.  33.]
  [ 43.  53.  63.  73.]
  [ 83.  93. 103. 113.]]

 [[123. 133. 143. 153.]
  [163. 173. 183. 193.]
  [203. 213. 223. 233.]]]
[[[  3  13  23  33]
  [ 43  53  63  73]
  [ 83  93 103 113]]

 [[123 133 143 153]
  [163 173 183 193]
  [203 213 223 233]]]


In [ ]:
np.delete(d, 1, axis = 0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [ ]:
np.delete(d, 1, axis = 1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [ ]:
np.delete(d, 1, axis = 2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

### Joining and Splitting Arrays

Concatenate, Stack, Split

In [ ]:
a = np.array([1,2,3,4]).reshape((2,2))
b = np.array([[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [ ]:
together = np.concatenate((a,b), axis = 0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
together.shape

(3, 2)

In [ ]:
together.ndim

2

In [ ]:
together[2,1] = 55
together

array([[ 1,  2],
       [ 3,  4],
       [ 5, 55]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
c = np.array([[1,2], [3,4]])*3+5
c

array([[ 8, 11],
       [14, 17]])

In [ ]:
np.concatenate((a,c), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 8, 11],
       [14, 17]])

In [ ]:
np.concatenate((a,c), axis = 1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [ ]:
np.concatenate((a,c), axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
mike

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

### Rearranging Array Elements

In [ ]:
import numpy as np

In [ ]:
first = np.array(np.arange(24))
second = first.reshape((3,8))
third = second.reshape((2,3,4))

In [ ]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
second

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
third

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### Flip Left to Right 

In [ ]:
second

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.fliplr(second)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [ ]:
third

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.fliplr(third)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

#### Flip Up and Down 

In [ ]:
np.flipud(third)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
np.roll(first, 5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [ ]:
np.roll(first, -5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [ ]:
third

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.roll(third, 2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [ ]:
second

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.rot90(second)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [ ]:
np.rot90(second, k = -1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

#### Splitting 

In [ ]:
temp = np.arange(6)
np.split(temp, 2)

[array([0, 1, 2]), array([3, 4, 5])]

In [ ]:
np.split(temp, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [ ]:
np.split(temp, 6)

[array([0]), array([1]), array([2]), array([3]), array([4]), array([5])]

In [ ]:
np.vectorize(len)(price)

array([3, 2, 5, 2, 6, 2, 9, 2])

### Copy and View methods

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[0] = 50
print('original arr', arr)
print('array copy', arr_copy)

original arr [1 2 3 4 5]
array copy [50  2  3  4  5]


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr2_view = arr2.view()

In [ ]:
arr2_view[0] = 48
print('original arr', arr2)
print('array view', arr2_view)

original arr [48  2  3  4  5]
array view [48  2  3  4  5]


In [ ]:
arr2[-1] = 100
print('original arr', arr2)
print('array view', arr2_view)

original arr [ 48   2   3   4 100]
array view [ 48   2   3   4 100]


In [ ]:
print (arr2_view.base)
print (arr_copy.base)

[ 48   2   3   4 100]
None


### Exercise 

Create an array with 5 dimensions containing the values 1,2,3,4 and check the dimension...

In [ ]:
arr = np.array([1,2,3,4], ndmin=5)
arr.shape

(1, 1, 1, 1, 4)

### Transpose-Like Operations

In [ ]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
second = first.reshape(3,8)
second

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
third = second.reshape(2,3,4)
third

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
first_trans = np.transpose(first)
first_trans

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
print(first.shape)
print(first_trans.shape)

(24,)
(24,)


In [ ]:
second_trans = np.transpose(second)
second_trans

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [ ]:
print(second.shape)
print(second_trans.shape)

(3, 8)
(8, 3)


In [ ]:
third

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### np.transpose(third)

In [ ]:
third_trans = np.transpose(third, axes=(0,2,1))
third_trans

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [ ]:
print(third.shape)
print(third_trans.shape)

(2, 3, 4)
(2, 4, 3)


**NOTE:** The axes parameter represents the positioning of the shape of the array. Initially our array is of the **form(shape) (2,3,4)** which means that the inital axes is by default **(0,1,2)**. Transposing it with the **axes = (0,2,1)** implies the transpose function should make our second axis to be third and the third axis to be second, which will in turn return **(2,4,3)**.

### Linear Algebra 

To install the sympy library use the command below:

`conda install sympy`

In [ ]:
from sympy import init_session
init_session()

# SymPy is a Python library for symbolic mathematics

# SymPy uses Unicode characters to render output in form of 
# pretty print. If you are using Python console for executing 
# SymPy session, the best pretty printing environment is activated 
# by calling init_session() function.

IPython console for SymPy 1.8 (Python 3.8.8-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.8/



In [ ]:
diff(x**3)

In [ ]:
diff(x**3, x, 2)

In [ ]:
diff((x**2 - 3*x + 5)**3)

In [ ]:
diff((x**2 - 3*x + 5)**3, x,2)